# -*- coding: utf-8 -*-
"""password_generator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ShXsSNggd2tTTAGtVbEwyuglN9jmZ5P4
"""

import random
import string

def generate_password():
    print(" Password Generator")

    try:
        length = int(input("Enter password length: "))

        if length <= 0:
            print("Please enter a positive number.")
            return

        characters = string.ascii_letters + string.digits + string.punctuation
        password = ""

        for i in range(length):
            password += random.choice(characters)

        print("Generated Password:", password)

    except ValueError:
        print("Invalid input! Please enter a number.")

generate_password()