# -*- coding: utf-8 -*-
"""rock_paper_scissors.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UFWaNSMTcUC03HqV-o9L2lg1xwVL1iO5
"""

import random

def play_game():
    print("Rock Paper Scissors")

    choices = ["rock", "paper", "scissors"]

    user_choice = input("Enter rock, paper, or scissors: ").lower()

    if user_choice not in choices:
        print("Invalid choice. Please choose rock, paper, or scissors.")
        return

    computer_choice = random.choice(choices)

    print("Computer chose:", computer_choice)

    if user_choice == computer_choice:
        print("It's a tie!")

    elif (user_choice == "rock" and computer_choice == "scissors") or \
         (user_choice == "paper" and computer_choice == "rock") or \
         (user_choice == "scissors" and computer_choice == "paper"):
        print("You win!")

    else:
        print("Computer wins!")

play_game()